# Ruby CircleCI 2.0 configuration file

version: 2
jobs:
  build1:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4.1-node-browsers

    steps:
      - checkout
      - run: echo "Hello World"
  build2:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4.1-node-browsers

    steps:
      - checkout
      - run: echo "Hello Again!"

  workflows:
    version: 2
    build1_and_build2:
      jobs:
       - build1
       - build2
       