# Ruby CircleCI 2.0 configuration file
dependencies:
  pre:
   - gem install bundler -v 1.14.5

version: 2
jobs:
  build1:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4.1-node-browsers

    steps:
      - checkout
      - run: echo "Build Passed!"    
      # - restore_cache:
      #     key: capy-{{ checksum "Gemfile.lock" }}

      # - save_cache:
      #     key: capy-{{ checksum "Gemfile.lock" }}
      #     paths:
      #      - vendor/bundle

      # - run: bundle install
      # - run: gem install cucumber
      # - run: gem install capybara
      # - run: gem install capybara-webkit
      # - run: gem install selenium-webdriver
      # - run: gem install rails
      # - run: gem install rspec
      # - run:



  build2:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4.1-node-browsers

    steps:
      - checkout
      - run: echo "Second Build Passed!"

workflows:
  version: 2
  build1_and_build2:
    jobs:
     - build1
     - build2:
        requires:  
           - build1
       