# Ruby CircleCI 2.0 configuration file
dependencies:
  pre:
   - gem install bundler -v 1.14.5

version: 2
jobs:
  Bundle_updates:
    docker:
      - image: circleci/ruby:2.6.0-node-browsers
        environment:
          BUNDLER_VERSION: 2.0.1

    steps:
      - checkout
      - restore_cache:
          key: bundler-{{checksum "Gemfile.lock"}}
      - save_cache:
          key: bundler-{{checksum "Gemfile.lock"}}
          paths:
            - vendor/bundle

      - run: gem install bundler:2.0.1
      - run: bundle update --bundler
      - run: cucumber --init

      # - run: bundle install
      # - run: gem install cucumber
      # - run: gem install capybara
      # - run: gem install capybara-webkit
      # - run: gem install selenium-webdriver
      # - run: gem install rails
      # - run: gem install rspec
 



  Capy_Tests:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.0-node-browsers

    steps:
      - checkout
      - run: gem install bundler:2.0.1
      - run: bundle update --bundler
      - run: mkdir -p ~/cucumber
      - run:
          name: Run Cukes without Failing
          command: |
            TESTFILES=$(circleci tests glob "features/**/*.feature" | circleci tests split --split-by=timings)
            DONT_FAIL=true bundle exec cucumber --tags 'not @wip' --format rerun --out rerun.txt --format pretty --format json --out ~/cucumber/tests.cucumber ${TESTFILES}

      - run: echo "Second Build Passed!"

workflows:
  version: 2
  build1_and_build2:
    jobs:
     - Bundle_updates
     - Capy_Tests:
        requires:  
           - Bundle_updates
       